name: Build SonicPad Debian Distro

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-distro:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y dosfstools e2fsprogs
      - name: Modify to allow sudo with qemu
        run: |
          sudo sed -i 's/:F$/:FC/' /usr/lib/binfmt.d/qemu-aarch64.conf
          sudo systemctl restart systemd-binfmt
          
      - name: Build rootfs
        run: |
          cd src
          sudo bash create_rootfs.sh

      - name: Pack EXT4 image
        run: |
          cd src
          sudo bash pack_img.sh

      - name: Upload image artifacts
        uses: actions/upload-artifact@v4
        with:
          name: sonicpad-images
          path: src/out/*.img



